name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login Docker Registry
      run: docker login -u ${{ secrets.REGISTRYUSERNAME }} -p ${{ secrets.REGISTRYPASSWORD }}
      
    - name: Build the Docker image
      run: docker build . --file sampleapp/Dockerfile --tag a1tan/fluxapp:latest #pull-$(GITHUB_SHA)
      
    - name: Push the Docker image
      run: docker push a1tan/fluxapp:latest #pull-$(GITHUB_SHA)
